# порт, на котором стартует сервер
server:
  port: 8888

# путь до конфигурационного файла логирования
logging:
  config: classpath:logback-spring.xml

# включает поддержку CORS для приложения
cors:
  allow: true

spring:
  # настройки подключения к БД
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/hospital_db
    username: root
    password: root

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  #    change-log: classpath:migrations/db.changelog-master.xml

  # конфигурация JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # конфигурация Spring MVC
  mvc:
    throw-exception-if-no-handler-found: true
    throw-404-if-no-handler-found: true

  # конфигурация Kafka
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: kafka:9092
      group-id: documents-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.template.example.documents.controllers.dto
    producer:
      acks: -1
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

